### ISSUE TITLE
前端 部分 

### ISSUE THREAD

**Issue by zcw-shio** [Gemini-D/actionview#89]
哥 空了整整这个前端呗 跑不起来啊

**Comment by limingxinleo** [comment]
Dockerfile里我写了怎么跑了。。

**Comment by zcw-shio** [comment]
不用docker成不成 哈哈

**Comment by zcw-shio** [comment]
缺app.js 与common.js能不能复制个

**Comment by limingxinleo** [comment]
你自己复制下啊。。。

**Comment by zcw-shio** [comment]
我就是去一个actionview复制的 但是请求路径都不一样呢 
![image](https://user-images.githubusercontent.com/66776428/186100180-d4a3acc8-1486-4e49-818f-7af88b121f06.png)
主要是咱们项目里没有这两个文件 
![image](https://user-images.githubusercontent.com/66776428/186100529-23a9bbfd-fb14-4667-9559-90fba373911d.png)

**Comment by limingxinleo** [comment]
![image](https://user-images.githubusercontent.com/16648551/186102541-d13bd6bf-f6ef-4fc6-8327-2f7e353de56d.png)

**Comment by limingxinleo** [comment]
你先 npm install && npm run build 试试

**Comment by zcw-shio** [comment]
![image](https://user-images.githubusercontent.com/66776428/186105273-1b036380-743c-40e7-8070-a981c7f03c4b.png)
哥 运行不动

**Comment by zcw-shio** [comment]
然后 您说的这两个文件
![image](https://user-images.githubusercontent.com/66776428/186107022-524d2caa-2d4b-4e92-aea6-8c51fb863c98.png) 怎么执行才能复制下来呢 我之前没用过docker 现在正在看教程

**Comment by limingxinleo** [comment]
你到前端目录执行啊。。。

cd front-end

**Comment by zcw-shio** [comment]
![image](https://user-images.githubusercontent.com/66776428/186115670-ae9eda6e-938f-4d69-be37-3b6788e66b6a.png)
![image](https://user-images.githubusercontent.com/66776428/186115817-778535a1-7635-4535-952a-9579ae3340d9.png)
![image](https://user-images.githubusercontent.com/66776428/186115904-a6e44ff4-927b-4c50-ae1d-f8ea693f1885.png)

**Comment by zcw-shio** [comment]
哥 我好像解决了

**Comment by zcw-shio** [comment]
不对 我尝试了下 确认是没有app.js 与common.js造成的 ，我按您说的 npm install && npm build ，但是压根就没有package.json文件 有一个lock文件 里面还是空的

**Comment by zcw-shio** [comment]
![image](https://user-images.githubusercontent.com/66776428/186130508-89bc29e0-9b1c-4e97-8509-b08bdadbba7d.png)

**Comment by zcw-shio** [comment]
哥  我错了 没仔细
